### ISSUE TITLE
nested stories don't work in vscode

### ISSUE THREAD

**Issue by hmontes** [orta/vscode-react-native-storybooks#27] opened 2018-01-17 16:43 UTC
Hi

According to the documentation: https://storybook.js.org/basics/writing-stories/#nesting-stories

We can do nesting with the stories. So, i made this example.

```
import React from 'react';
import { View, Text } from 'react-native';

import { storiesOf } from '@storybook/react-native';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';

import { Background, Input } from './';

storiesOf('CC/DD/Inputs', module)
  .addDecorator(story => (
    <Background style={styles.center}>
      <View style={{ alignSelf: 'stretch' }}>{story()}</View>
    </Background>
  ))
  .add('Email', () => <Input />)
  .add('Password', () => <Input pass />);

storiesOf('CC/DD/Backgrounds', module).add('Gradiente Azul', () => (
  <Background />
));
```

In the web browser:

<img width="150" alt="captura de pantalla 2018-01-17 a la s 13 42 18" src="https://user-images.githubusercontent.com/7022970/35054817-5a1836e0-fb8c-11e7-8f66-8afed320778f.png">

But in VSCODE.

<img width="255" alt="captura de pantalla 2018-01-17 a la s 13 43 20" src="https://user-images.githubusercontent.com/7022970/35054839-680447d0-fb8c-11e7-8b07-1f7979ef982d.png">

The nesting don't work.

Thank you

**Comment by orta** [comment] 2018-01-18 00:00
Nope, you're welcome to add it though 👍 - dupe of https://github.com/orta/vscode-react-native-storybooks/issues/13

**Closed by orta** 2018-01-18 00:00 UTC
